#!/bin/sh

mkdir -p /var/www
chown -Rf nginx:nginx /var/www
mkdir -p /tmp/nginx/client-body
chown -R nginx /tmp/nginx
mkdir -p /var/log/nginx
touch /var/log/nginx/access.log
touch /var/log/nginx/error.log
